require('dotenv').config()

const {
    TOKEN_SECRET,
    DATABASE_URL,
    ORACLE_DATABASE_URL,
    ORACLE_DATABASE_USER,
    ORACLE_DATABASE_PASSWORD,
    ORACLE_DATABASE_SERVICE
} = process.env

module.exports = {
    DATABASE_URL,
    TOKEN_SECRET,
    ORACLE_DATABASE_URL,
    ORACLE_DATABASE_USER,
    ORACLE_DATABASE_PASSWORD,
    ORACLE_DATABASE_SERVICE
}
