require('dotenv').config()

const {
    TOKEN_SECRET,
    DATABASE_URL,
    ORACLE_DATABASE_URL,
    ORACLE_DATABASE_USER,
    ORACLE_DATABASE_PASSWORD,
    ORACLE_DATABASE_SERVICE,
    ETHESIS_USERNAME,
    ETHESIS_PASSWORD,
    ETHESIS_BASE_URL,
    ETHESIS_UPLOAD_CRON,
    URN_GENERATOR_ADDRESS
} = process.env

module.exports = {
    DATABASE_URL,
    TOKEN_SECRET,
    ORACLE_DATABASE_URL,
    ORACLE_DATABASE_USER,
    ORACLE_DATABASE_PASSWORD,
    ORACLE_DATABASE_SERVICE,
    ETHESIS_USERNAME,
    ETHESIS_PASSWORD,
    ETHESIS_BASE_URL,
    ETHESIS_UPLOAD_CRON,
    URN_GENERATOR_ADDRESS
}
