require('dotenv').config()

const {
    ETHESIS_USERNAME,
    ETHESIS_PASSWORD,
    ETHESIS_BASE_URL,
    ETHESIS_UPLOAD_CRON,
    URN_GENERATOR_ADDRESS,
    TOKEN_SECRET,
    DATABASE_URL
} = process.env

module.exports = {
    ETHESIS_USERNAME,
    ETHESIS_PASSWORD,
    ETHESIS_BASE_URL,
    ETHESIS_UPLOAD_CRON,
    URN_GENERATOR_ADDRESS,
    DATABASE_URL,
    TOKEN_SECRET
}
