Create user gradu identified by gradu;

GRANT create session TO gradu;
GRANT create table TO gradu;
GRANT create view TO gradu;
GRANT create any trigger TO gradu;
GRANT create any procedure TO gradu;
GRANT create sequence TO gradu;
GRANT create synonym TO gradu;
GRANT UNLIMITED TABLESPACE TO gradu;

--------------------------------------------------------
--  File created - Wednesday-November-14-2018
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence GTUNNUS
--------------------------------------------------------

   CREATE SEQUENCE  "GRADU"."GTUNNUS"  MINVALUE 30000 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 32429 CACHE 2 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence HTUNNUS
--------------------------------------------------------

   CREATE SEQUENCE  "GRADU"."HTUNNUS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 165 CACHE 2 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence KTUNNUS
--------------------------------------------------------

   CREATE SEQUENCE  "GRADU"."KTUNNUS"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 71 CACHE 2 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence OKTUNNUS
--------------------------------------------------------

   CREATE SEQUENCE  "GRADU"."OKTUNNUS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 525 CACHE 2 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence OTUNNUS
--------------------------------------------------------

   CREATE SEQUENCE  "GRADU"."OTUNNUS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 5258 CACHE 2 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence TTUNNUS
--------------------------------------------------------

   CREATE SEQUENCE  "GRADU"."TTUNNUS"  MINVALUE 210000 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 212845 CACHE 2 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table EKAT
--------------------------------------------------------

  CREATE TABLE "GRADU"."EKAT"
   (	"EKAP" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRADU
--------------------------------------------------------

  CREATE TABLE "GRADU"."GRADU"
   (	"TUNNUS" NUMBER(10,0),
	"OTSAKE" VARCHAR2(200 BYTE),
	"KIRJAUSPVM" DATE,
	"AIHE_URI" VARCHAR2(150 BYTE),
	"AIHE_KUVAUS" VARCHAR2(2000 BYTE),
	"LUONNE" VARCHAR2(30 BYTE),
	"LAAJUUS" VARCHAR2(30 BYTE),
	"VALMISTELIJA" VARCHAR2(30 BYTE),
	"VALMISTELULINJA" VARCHAR2(30 BYTE),
	"ASIAKAS" VARCHAR2(200 BYTE),
	"SALAUS" VARCHAR2(30 BYTE),
	"VAHVISTUSPVM" DATE,
	"VAHVISTAJALINJA" VARCHAR2(30 BYTE),
	"VAHVISTAJA" VARCHAR2(30 BYTE),
	"VARAUSPVM" DATE,
	"TEKIJA" VARCHAR2(11 BYTE),
	"STIPENDI" VARCHAR2(30 BYTE),
	"TILA" VARCHAR2(30 BYTE),
	"TILA_PVM" DATE,
	"MAARA_AIKA" DATE,
	"MAARA_AJAN_VIIM_MUUTOS_PVM" DATE,
	"MAARA_AJAN_TYYPPI" VARCHAR2(30 BYTE),
	"SUUNNITHYVPVM" DATE,
	"ARVOSANA" VARCHAR2(30 BYTE),
	"KESKEYTYSSYY" VARCHAR2(250 BYTE),
	"HALLINTOKOMMENTTI" VARCHAR2(1000 BYTE),
	"KLOONATTU" NUMBER(10,0),
	"OHETU" VARCHAR2(11 BYTE),
	"OPNRO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 335872 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORIAMERKINTA
--------------------------------------------------------

  CREATE TABLE "GRADU"."HISTORIAMERKINTA"
   (	"HTUNNUS" NUMBER(11,0),
	"GRADUTUNNUS" NUMBER(10,0),
	"KIRJAAJA" VARCHAR2(30 BYTE),
	"SALAINEN" NUMBER(1,0) DEFAULT 0,
	"KIRJAUSPVM" DATE,
	"KOMMENTTI" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORIAMERKINTA_OLD
--------------------------------------------------------

  CREATE TABLE "GRADU"."HISTORIAMERKINTA_OLD"
   (	"GRADUTUNNUS" NUMBER(10,0),
	"KIRJAAJA" VARCHAR2(30 BYTE),
	"SALAINEN" NUMBER(1,0) DEFAULT 0,
	"KIRJAUSPVM" DATE,
	"KOMMENTTI" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOODI
--------------------------------------------------------

  CREATE TABLE "GRADU"."KOODI"
   (	"KOODITUNNUS" NUMBER(5,0),
	"SARAKE" VARCHAR2(30 BYTE),
	"ARVO" VARCHAR2(30 BYTE),
	"SELITYS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LINJA
--------------------------------------------------------

  CREATE TABLE "GRADU"."LINJA"
   (	"TUNNUS" VARCHAR2(30 BYTE),
	"NIMI" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OHJAAJA
--------------------------------------------------------

  CREATE TABLE "GRADU"."OHJAAJA"
   (	"KTUNNUS" VARCHAR2(30 BYTE),
	"OIKEUSLUOKKA" NUMBER(1,0) DEFAULT 0,
	"SUKUNIMI" VARCHAR2(80 BYTE),
	"ETUNIMI" VARCHAR2(30 BYTE),
	"OPPIARVO" VARCHAR2(30 BYTE),
	"LINJA" VARCHAR2(30 BYTE),
	"YHTEISO" VARCHAR2(200 BYTE),
	"SPOSTI" VARCHAR2(80 BYTE),
	"TKTL_TUNNUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OHJAUS
--------------------------------------------------------

  CREATE TABLE "GRADU"."OHJAUS"
   (	"OTUNNUS" NUMBER(11,0),
	"GRADUTUNNUS" NUMBER(10,0),
	"OHJAAJATUNNUS" VARCHAR2(30 BYTE),
	"ROOLI" VARCHAR2(30 BYTE),
	"ALKAMISAIKA" DATE,
	"PAATTYMISAIKA" DATE,
	"PAATTYMISSYY" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 212992 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARKASTAJA
--------------------------------------------------------

  CREATE TABLE "GRADU"."TARKASTAJA"
   (	"TARKASTUSTUNNUS" NUMBER(11,0),
	"OHJAAJATUNNUS" VARCHAR2(30 BYTE),
	"ROOLI" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 90112 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARKASTAJA_OLD
--------------------------------------------------------

  CREATE TABLE "GRADU"."TARKASTAJA_OLD"
   (	"TARKASTUSTUNNUS" NUMBER(10,0),
	"OHJAAJATUNNUS" VARCHAR2(30 BYTE),
	"ROOLI" VARCHAR2(30 BYTE),
	"FK_TARKASTUSTUNNUS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARKASTUS
--------------------------------------------------------

  CREATE TABLE "GRADU"."TARKASTUS"
   (	"TTUNNUS" NUMBER(10,0),
	"GRADUTUNNUS" NUMBER(10,0),
	"KIRJAAJA" VARCHAR2(30 BYTE),
	"VAIHE" VARCHAR2(30 BYTE),
	"JATETTY_PVM" DATE,
	"TARKASTETTU_PVM" DATE,
	"TULOS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARKASTUS_OLD
--------------------------------------------------------

  CREATE TABLE "GRADU"."TARKASTUS_OLD"
   (	"TTUNNUS" NUMBER(10,0),
	"GRADUTUNNUS" NUMBER(10,0),
	"KIRJAAJA" VARCHAR2(30 BYTE),
	"VAIHE" VARCHAR2(30 BYTE),
	"JATETTY_PVM" DATE,
	"TARKISTETTU_PVM" DATE,
	"TULOS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARKISTUS
--------------------------------------------------------

  CREATE TABLE "GRADU"."TARKISTUS"
   (	"TUNNUS" NUMBER(10,0),
	"GRADUTUNNUS" NUMBER(10,0),
	"VAIHE" VARCHAR2(30 BYTE),
	"JATETTY_PVM" DATE,
	"TARKISTETTU_PVM" DATE,
	"TULOS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VANHA_OHJAUS
--------------------------------------------------------

  CREATE TABLE "GRADU"."VANHA_OHJAUS"
   (	"TUNNUS" NUMBER(11,0),
	"GRADUTUNNUS" NUMBER(10,0),
	"OHJAAJATUNNUS" VARCHAR2(30 BYTE),
	"ROOLI" VARCHAR2(30 BYTE),
	"ALKAMISAIKA" DATE,
	"PAATTYMISAIKA" DATE,
	"PAATTYMISSYY" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 90112 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VANHA_OHJAUS2
--------------------------------------------------------

  CREATE TABLE "GRADU"."VANHA_OHJAUS2"
   (	"GRADUTUNNUS" NUMBER(10,0),
	"OHJAAJATUNNUS" VARCHAR2(30 BYTE),
	"ROOLI" VARCHAR2(30 BYTE),
	"ALKAMISAIKA" DATE,
	"PAATTYMISAIKA" DATE,
	"PAATTYMISSYY" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 90112 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View OHJAAJIEN_GRADULKM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GRADU"."OHJAAJIEN_GRADULKM" ("KTUNNUS", "NIMI", "LKM") AS
  select ohjaaja.ktunnus, sukunimi||' '||etunimi nimi , count(*) lkm
from ohjaaja, tarkastaja, tarkastus
where tarkastus.ttunnus=tarkastaja.tarkastustunnus and
ohjaaja.ktunnus=tarkastaja.ohjaajatunnus and
tarkastus.vaihe='gradu'  and tulos != 'korjattava'
and tarkastus.tarkastettu_pvm between date '2007-08-01' and date '2008-07-31'
group by ohjaaja.ktunnus, sukunimi||' '||etunimi

;
--------------------------------------------------------
--  DDL for View OHJAAJIEN_GRADU_LKM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GRADU"."OHJAAJIEN_GRADU_LKM" ("KTUNNUS", "NIMI", "LKM") AS
  select ohjaaja.ktunnus, sukunimi||' '||etunimi nimi , count(*) lkm
from ohjaaja, tarkastaja, tarkastus
where tarkastus.ttunnus=tarkastaja.tarkastustunnus and
ohjaaja.ktunnus=tarkastaja.ohjaajatunnus and
tarkastus.vaihe='gradu'  and tulos like 'hyv%'
and tarkastus.tarkastettu_pvm between date '2007-08-01' and date '2008-07-31'
group by ohjaaja.ktunnus, sukunimi||' '||etunimi

;
--------------------------------------------------------
--  DDL for View TARKISTAJA_LKM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GRADU"."TARKISTAJA_LKM" ("TARKASTUSTUNNUS", "LKM") AS
  select tarkastustunnus, count(*) lkm
from tarkastaja
group by tarkastustunnus

;
--------------------------------------------------------
--  DDL for View YKKOSOHJAAJIEN_GRADULKM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GRADU"."YKKOSOHJAAJIEN_GRADULKM" ("KTUNNUS", "NIMI", "LKM") AS
  select ohjaaja.ktunnus, sukunimi||' '||etunimi nimi , count(*) lkm
from ohjaaja, ohjaus, tarkastaja, tarkastus
where tarkastus.ttunnus=tarkastaja.tarkastustunnus and
 tarkastus.gradutunnus=ohjaus.gradutunnus and
ohjaaja.ktunnus=tarkastaja.ohjaajatunnus and
tarkastaja.ohjaajatunnus=ohjaus.Ohjaajatunnus and
ohjaus.rooli like 'p%' and
tarkastus.vaihe='gradu'
and tarkastus.tarkastettu_pvm between date '2007-08-01' and date '2008-07-31'
and ohjaus.paattymissyy like 'Gradu hyv%'
group by ohjaaja.ktunnus, sukunimi||' '||etunimi

;
--------------------------------------------------------
--  DDL for View YKKOSOHJAUS_GRADULKM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GRADU"."YKKOSOHJAUS_GRADULKM" ("KTUNNUS", "NIMI", "LKM") AS
  select ohjaaja.ktunnus, sukunimi||' '||etunimi nimi , count(*) lkm
from ohjaaja, ohjaus, tarkastaja, tarkastus
where tarkastus.ttunnus=tarkastaja.tarkastustunnus and
 tarkastus.gradutunnus=ohjaus.gradutunnus and
ohjaaja.ktunnus=tarkastaja.ohjaajatunnus and
tarkastaja.ohjaajatunnus=ohjaus.Ohjaajatunnus and
ohjaus.rooli like 'p%' and
tarkastus.vaihe='gradu'  and
tulos !='korjattava'
and tarkastus.tarkastettu_pvm between date '2007-08-01' and date '2008-07-31'
and ohjaus.paattymissyy like 'Gradu hyv%'
group by ohjaaja.ktunnus, sukunimi||' '||etunimi

;
--------------------------------------------------------
--  DDL for Index PK_GRADU
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_GRADU" ON "GRADU"."GRADU" ("TUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TARKASTUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_TARKASTUS" ON "GRADU"."TARKASTUS" ("TTUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TARKISTUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_TARKISTUS" ON "GRADU"."TARKISTUS" ("TUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_OHJAAJA
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_OHJAAJA" ON "GRADU"."OHJAAJA" ("KTUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_KOODIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_KOODIT" ON "GRADU"."KOODI" ("KOODITUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_HISTORIAMERKINTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_HISTORIAMERKINTA" ON "GRADU"."HISTORIAMERKINTA" ("HTUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 49152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_KOODI
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."UNIQUE_KOODI" ON "GRADU"."KOODI" ("SARAKE", "ARVO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LINJA
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_LINJA" ON "GRADU"."LINJA" ("TUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_OHJAUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."PK_OHJAUS" ON "GRADU"."OHJAUS" ("OTUNNUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index YKSI_TARKASTUS_PER_PAIVA
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRADU"."YKSI_TARKASTUS_PER_PAIVA" ON "GRADU"."TARKASTUS" ("GRADUTUNNUS", "TARKASTETTU_PVM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 90112 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VANHA_OHJAUS2
--------------------------------------------------------

  ALTER TABLE "GRADU"."VANHA_OHJAUS2" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."VANHA_OHJAUS2" MODIFY ("OHJAAJATUNNUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TARKASTAJA_OLD
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTAJA_OLD" MODIFY ("TARKASTUSTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKASTAJA_OLD" MODIFY ("OHJAAJATUNNUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VANHA_OHJAUS
--------------------------------------------------------

  ALTER TABLE "GRADU"."VANHA_OHJAUS" MODIFY ("TUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."VANHA_OHJAUS" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."VANHA_OHJAUS" MODIFY ("OHJAAJATUNNUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EKAT
--------------------------------------------------------

  ALTER TABLE "GRADU"."EKAT" MODIFY ("EKAP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TARKASTUS_OLD
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTUS_OLD" MODIFY ("TTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKASTUS_OLD" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TARKASTAJA
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTAJA" MODIFY ("TARKASTUSTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKASTAJA" MODIFY ("OHJAAJATUNNUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINJA
--------------------------------------------------------

  ALTER TABLE "GRADU"."LINJA" MODIFY ("TUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."LINJA" ADD CONSTRAINT "PK_LINJA" PRIMARY KEY ("TUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TARKISTUS
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKISTUS" MODIFY ("TUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKISTUS" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKISTUS" ADD CONSTRAINT "PK_TARKISTUS" PRIMARY KEY ("TUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KOODI
--------------------------------------------------------

  ALTER TABLE "GRADU"."KOODI" MODIFY ("KOODITUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."KOODI" MODIFY ("SARAKE" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."KOODI" MODIFY ("ARVO" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."KOODI" ADD CONSTRAINT "PK_KOODIT" PRIMARY KEY ("KOODITUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRADU"."KOODI" ADD CONSTRAINT "UNIQUE_KOODI" UNIQUE ("SARAKE", "ARVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TARKASTUS
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTUS" MODIFY ("TTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKASTUS" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."TARKASTUS" ADD CONSTRAINT "PK_TARKASTUS" PRIMARY KEY ("TTUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OHJAUS
--------------------------------------------------------

  ALTER TABLE "GRADU"."OHJAUS" MODIFY ("OTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."OHJAUS" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."OHJAUS" MODIFY ("OHJAAJATUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."OHJAUS" ADD CONSTRAINT "PK_OHJAUS" PRIMARY KEY ("OTUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRADU
--------------------------------------------------------

  ALTER TABLE "GRADU"."GRADU" MODIFY ("TUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."GRADU" MODIFY ("OTSAKE" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."GRADU" MODIFY ("KIRJAUSPVM" NOT NULL DISABLE);
  ALTER TABLE "GRADU"."GRADU" MODIFY ("TILA" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."GRADU" ADD CONSTRAINT "PK_GRADU" PRIMARY KEY ("TUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 57344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIAMERKINTA_OLD
--------------------------------------------------------

  ALTER TABLE "GRADU"."HISTORIAMERKINTA_OLD" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA_OLD" MODIFY ("KIRJAAJA" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA_OLD" MODIFY ("SALAINEN" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA_OLD" MODIFY ("KIRJAUSPVM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OHJAAJA
--------------------------------------------------------

  ALTER TABLE "GRADU"."OHJAAJA" MODIFY ("KTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."OHJAAJA" ADD CONSTRAINT "PK_OHJAAJA" PRIMARY KEY ("KTUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRADU"."OHJAAJA" ADD UNIQUE ("TKTL_TUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIAMERKINTA
--------------------------------------------------------

  ALTER TABLE "GRADU"."HISTORIAMERKINTA" MODIFY ("HTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA" MODIFY ("GRADUTUNNUS" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA" MODIFY ("KIRJAAJA" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA" MODIFY ("SALAINEN" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA" MODIFY ("KIRJAUSPVM" NOT NULL ENABLE);
  ALTER TABLE "GRADU"."HISTORIAMERKINTA" ADD CONSTRAINT "PK_HISTORIAMERKINTA" PRIMARY KEY ("HTUNNUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 49152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRADU
--------------------------------------------------------

  ALTER TABLE "GRADU"."GRADU" ADD CONSTRAINT "FK_VALMISTELIJA" FOREIGN KEY ("VALMISTELIJA")
	  REFERENCES "GRADU"."OHJAAJA" ("KTUNNUS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIAMERKINTA
--------------------------------------------------------

  ALTER TABLE "GRADU"."HISTORIAMERKINTA" ADD CONSTRAINT "FK_HGRADUTUNNUS" FOREIGN KEY ("GRADUTUNNUS")
	  REFERENCES "GRADU"."GRADU" ("TUNNUS") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GRADU"."HISTORIAMERKINTA" ADD CONSTRAINT "FK_KIRJAAJA" FOREIGN KEY ("KIRJAAJA")
	  REFERENCES "GRADU"."OHJAAJA" ("KTUNNUS") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OHJAAJA
--------------------------------------------------------

  ALTER TABLE "GRADU"."OHJAAJA" ADD CONSTRAINT "FK_OLINJA" FOREIGN KEY ("LINJA")
	  REFERENCES "GRADU"."LINJA" ("TUNNUS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OHJAUS
--------------------------------------------------------

  ALTER TABLE "GRADU"."OHJAUS" ADD CONSTRAINT "FK_OGRADUTUNNUS" FOREIGN KEY ("GRADUTUNNUS")
	  REFERENCES "GRADU"."GRADU" ("TUNNUS") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GRADU"."OHJAUS" ADD CONSTRAINT "FK_OOHJAAJATUNNUS" FOREIGN KEY ("OHJAAJATUNNUS")
	  REFERENCES "GRADU"."OHJAAJA" ("KTUNNUS") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARKASTAJA
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTAJA" ADD CONSTRAINT "FK_TARKASTUSTUNNUS" FOREIGN KEY ("TARKASTUSTUNNUS")
	  REFERENCES "GRADU"."TARKASTUS" ("TTUNNUS") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GRADU"."TARKASTAJA" ADD CONSTRAINT "FK_TOHJAAJATUNNUS" FOREIGN KEY ("OHJAAJATUNNUS")
	  REFERENCES "GRADU"."OHJAAJA" ("KTUNNUS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARKASTAJA_OLD
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTAJA_OLD" ADD FOREIGN KEY ("FK_TARKASTUSTUNNUS")
	  REFERENCES "GRADU"."TARKASTUS" ("TTUNNUS") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARKASTUS
--------------------------------------------------------

  ALTER TABLE "GRADU"."TARKASTUS" ADD CONSTRAINT "FK_TGRADUTUNNUS" FOREIGN KEY ("GRADUTUNNUS")
	  REFERENCES "GRADU"."GRADU" ("TUNNUS") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GRADU"."TARKASTUS" ADD CONSTRAINT "FK_TKIRJAAJA" FOREIGN KEY ("KIRJAAJA")
	  REFERENCES "GRADU"."OHJAAJA" ("KTUNNUS") ENABLE;
